"""0002_change tracked_items.last_price to numeric

Revision ID: 93e8ca39a31a
Revises: b18d263e0920
Create Date: 2026-04-22 14:02:36.999210

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "93e8ca39a31a"
down_revision: Union[str, Sequence[str], None] = "b18d263e0920"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tracked_items",
        "last_price",
        existing_type=sa.INTEGER(),
        type_=sa.Numeric(precision=12, scale=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tracked_items",
        "last_price",
        existing_type=sa.Numeric(precision=12, scale=2),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
