"""0003_change tracked_items.threshold to numeric

Revision ID: f1ba500d7847
Revises: 93e8ca39a31a
Create Date: 2026-04-22 15:04:57.972621

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1ba500d7847"
down_revision: Union[str, Sequence[str], None] = "93e8ca39a31a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tracked_items",
        "threshold",
        existing_type=sa.INTEGER(),
        type_=sa.Numeric(precision=12, scale=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tracked_items",
        "threshold",
        existing_type=sa.Numeric(precision=12, scale=2),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
