apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wboz.fullname" . }}-config
  labels:
    {{- include "wboz.labels" . | nindent 4 }}
data:
  APP_ENVIRONMENT: {{ .Values.app.environment | quote }}
  DEBUG: {{ .Values.app.debug | quote }}
  APP_SERVICE_NAME: {{ .Values.app.serviceName | quote }}
  API_HOST: "0.0.0.0"
  API_PORT: {{ .Values.app.apiPort | quote }}
  REQUESTS_TIMEOUT: {{ .Values.app.requestsTimeout | quote }}
  DEFAULT_THRESHOLD: {{ .Values.app.defaultThreshold | quote }}
  DEFAULT_CHECK_INTERVAL: {{ .Values.app.defaultCheckInterval | quote }}
  THRESHOLD_ALERT_COOLDOWN_HOURS: {{ .Values.app.thresholdAlertCooldownHours | quote }}
  DATABASE_POOL_SIZE: {{ .Values.app.databasePoolSize | quote }}
  DATABASE_POOL_MAX_OVERFLOW: {{ .Values.app.databasePoolMaxOverflow | quote }}
  DATABASE_POOL_TIMEOUT: {{ .Values.app.databasePoolTimeout | quote }}
  POSTGRES_DB: {{ .Values.postgres.db | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
